### ISSUE TITLE
Slows down my app

### ISSUE THREAD

**Issue by IgorGanapolsky** [scottyab/secure-preferences#23] opened 2015-07-21 16:18 UTC
Hello,
ever since I upgraded to <b>0.0.1</b> from <b>0.0.4</b>, my app has experienced tremendous slowdown.  I mean like 10x slower!  Any ideas what the issue could be here?

Thanks,
Igor

**Comment by scottyab** [comment] 2015-07-21 16:24
hmm, I'm assuming you talking specifically get/put secure prefs? as the init slowness is covered in another issue.  Do you have any tests or sample code we could review and specific timings? a library like [Hugo](https://github.com/JakeWharton/hugo) might help?  also do you mean 0.1.0 not 0.0.1

**Comment by IgorGanapolsky** [comment] 2015-07-21 16:26
I mean <b>0.1.1</b>.  I don't know how to create tests for this yet, I'll look into Hugo.  But I can tell you without a shadow of doubt that downgrading back to 0.0.4 made my app faster again.

**Comment by scottyab** [comment] 2015-07-21 16:35
That figures as the 0.1.x change was pretty big and replaced the core crypto used by Secure Prefs making it stronger. If you see issue #18 we are looking to add a way of providing your own key which you can generate quicker if you're wanting performance over security. The default is higher security. When I get chance I'll add an async way of initialising Secure Prefs. 

* Are you seeing the slowness when you init or put/get?
* What size of strings are you storing? I was just thinking if they were large that could be why you're seeing slowness

**Comment by IgorGanapolsky** [comment] 2015-07-21 16:39
I am seeing slowness when I init.  Then my whole app comes down to a crawl.  The size of strings are small, less than few dozen characters - primarily an auth token from the server.

**Comment by scottyab** [comment] 2015-07-21 16:42
Ok, right. In the next version 0.1.3, we should have a way of speeding the init up. Although once it's instantiated it should be ok. I'll create a task to review performance differences between secure prefs and standard shared prefs

**Comment by scottyab** [comment] 2015-07-23 12:11
Closed as duplicate of #18

**Closed by scottyab** 2015-07-23 12:11 UTC
