### ISSUE TITLE
After upgrade Android OS Version 9 (pie) the values are not stored and retrieved.

### ISSUE THREAD

**Issue by vinojvetha** [scottyab/secure-preferences#93] opened 2019-03-11 09:59 UTC

**Comment by vinojvetha** [comment] 2019-03-11 09:59
Anybody have you faced this problem??.

**Comment by kyuseokyi** [comment] 2019-03-12 01:10
salt value changed on the pie. you can check here
https://github.com/scottyab/secure-preferences/pull/92

**Comment by scottyab** [comment] 2019-03-12 10:26
duplicate of #88, Thanks for raising. The 0.1.7 release gives an option to pass you're own salt

**Closed by scottyab** 2019-03-12 10:26 UTC

**Comment by nitin525** [comment] 2019-10-01 10:05
would upgrading the lib from 0.1.5 to 0.1.7 take care of the app upgrade issue or we need to have two separate constructors? One for 28 and above?

**Comment by nitin525** [comment] 2019-10-01 10:22
> duplicate of #88, Thanks for raising. The 0.1.7 release gives an option to pass you're own salt

would upgrading the lib from 0.1.5 to 0.1.7 take care of the app upgrade issue or we need to have two separate constructors? One for 28 and above with a salt?
